import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const distDir = resolve(root, "dist");
const edgeSource = resolve(root, "edge/speedtest-edge.js");
const edgeOutDir = resolve(root, "dist-edge");
const edgeOut = resolve(edgeOutDir, "edge.js");
const minTokenLength = 32;

const textTypes = new Set([
  ".html",
  ".css",
  ".js",
  ".mjs",
  ".json",
  ".svg",
  ".txt",
  ".map",
  ".webmanifest"
]);

const contentTypes = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".webmanifest": "application/manifest+json; charset=utf-8"
};

async function walk(dir) {
  const entries = await readdir(dir);
  const files = [];
  for (const entry of entries) {
    const path = join(dir, entry);
    const info = await stat(path);
    if (info.isDirectory()) {
      files.push(...(await walk(path)));
    } else if (info.isFile()) {
      files.push(path);
    }
  }
  return files;
}

const files = await walk(distDir);
const assets = {};
const buildConfig = readBuildConfig();

for (const file of files) {
  const ext = extname(file).toLowerCase();
  const bytes = await readFile(file);
  const route = `/${relative(distDir, file).replaceAll("\\", "/")}`;
  const isText = textTypes.has(ext);
  assets[route] = {
    contentType: contentTypes[ext] || "application/octet-stream",
    encoding: isText ? "text" : "base64",
    body: isText ? bytes.toString("utf8") : bytes.toString("base64"),
    etag: `"${createHash("sha256").update(bytes).digest("hex").slice(0, 16)}"`
  };
}

if (!assets["/index.html"]) {
  throw new Error("dist/index.html not found");
}

const prefix = [
  "/* Generated by tools/inline-static.mjs. Deploy this single file to ESA EdgeRoutine. */",
  "/* This file may contain build-time secrets. Do not commit dist-edge/edge.js to a public repository. */",
  `globalThis.__SPEEDTEST_BUILD_CONFIG__ = ${JSON.stringify(buildConfig)};`,
  `globalThis.__SPEEDTEST_STATIC_ASSETS__ = ${JSON.stringify(assets)};`,
  ""
].join("\n");

await mkdir(edgeOutDir, { recursive: true });
await writeFile(edgeOut, `${prefix}${await readFile(edgeSource, "utf8")}`);

const size = Buffer.byteLength(await readFile(edgeOut));
console.log(`wrote ${edgeOut}`);
console.log(`edge bundle size ${(size / 1024).toFixed(1)} KiB`);
if (size > 4 * 1024 * 1024) {
  console.warn("warning: edge bundle is larger than the 4 MiB EdgeRoutine code package limit");
}
if (buildConfig.accessTokens?.length > 0) {
  console.log(`embedded ${buildConfig.accessTokens.length} access token(s) for ESA deployment`);
}

function readBuildConfig() {
  const accessTokens = unique([
    ...splitEnv(process.env.SPEEDTEST_TOKEN),
    ...splitEnv(process.env.SPEEDTEST_TOKENS)
  ]);
  const allowedOrigins = unique(splitEnv(process.env.SPEEDTEST_ALLOWED_ORIGINS));

  validateTokens(accessTokens);

  const config = {};
  if (accessTokens.length > 0) config.accessTokens = accessTokens;
  if (allowedOrigins.length > 0) config.allowedOrigins = allowedOrigins;
  return config;
}

function splitEnv(value) {
  if (!value) return [];
  return String(value)
    .split(/[,\n\r]+/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function unique(values) {
  return [...new Set(values)];
}

function validateTokens(tokens) {
  for (const token of tokens) {
    if (token.length < minTokenLength) {
      throw new Error(`SPEEDTEST_TOKEN entries must be at least ${minTokenLength} characters long`);
    }
    if (/\s/.test(token)) {
      throw new Error("SPEEDTEST_TOKEN entries must not contain whitespace");
    }
    if (/replace|example|secret|password|token/i.test(token)) {
      throw new Error("SPEEDTEST_TOKEN appears to contain placeholder text");
    }
  }
}
